# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/cmake/1530/bin/cmake

# The command to remove a file.
RM = /snap/cmake/1530/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/cristian/Desktop/Argus-OOP-Project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/cristian/Desktop/Argus-OOP-Project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/snap/cmake/1530/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/snap/cmake/1530/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/snap/cmake/1530/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/snap/cmake/1530/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/snap/cmake/1530/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/snap/cmake/1530/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/snap/cmake/1530/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/snap/cmake/1530/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cristian/Desktop/Argus-OOP-Project/CMakeFiles /home/cristian/Desktop/Argus-OOP-Project//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cristian/Desktop/Argus-OOP-Project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named oop

# Build rule for target.
oop: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 oop
.PHONY : oop

# fast build rule for target.
oop/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oop.dir/build.make CMakeFiles/oop.dir/build
.PHONY : oop/fast

src/Alert.o: src/Alert.cpp.o
.PHONY : src/Alert.o

# target to build an object file
src/Alert.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oop.dir/build.make CMakeFiles/oop.dir/src/Alert.cpp.o
.PHONY : src/Alert.cpp.o

src/Alert.i: src/Alert.cpp.i
.PHONY : src/Alert.i

# target to preprocess a source file
src/Alert.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oop.dir/build.make CMakeFiles/oop.dir/src/Alert.cpp.i
.PHONY : src/Alert.cpp.i

src/Alert.s: src/Alert.cpp.s
.PHONY : src/Alert.s

# target to generate assembly for a file
src/Alert.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oop.dir/build.make CMakeFiles/oop.dir/src/Alert.cpp.s
.PHONY : src/Alert.cpp.s

src/CPUMetric.o: src/CPUMetric.cpp.o
.PHONY : src/CPUMetric.o

# target to build an object file
src/CPUMetric.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oop.dir/build.make CMakeFiles/oop.dir/src/CPUMetric.cpp.o
.PHONY : src/CPUMetric.cpp.o

src/CPUMetric.i: src/CPUMetric.cpp.i
.PHONY : src/CPUMetric.i

# target to preprocess a source file
src/CPUMetric.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oop.dir/build.make CMakeFiles/oop.dir/src/CPUMetric.cpp.i
.PHONY : src/CPUMetric.cpp.i

src/CPUMetric.s: src/CPUMetric.cpp.s
.PHONY : src/CPUMetric.s

# target to generate assembly for a file
src/CPUMetric.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oop.dir/build.make CMakeFiles/oop.dir/src/CPUMetric.cpp.s
.PHONY : src/CPUMetric.cpp.s

src/DiskMetric.o: src/DiskMetric.cpp.o
.PHONY : src/DiskMetric.o

# target to build an object file
src/DiskMetric.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oop.dir/build.make CMakeFiles/oop.dir/src/DiskMetric.cpp.o
.PHONY : src/DiskMetric.cpp.o

src/DiskMetric.i: src/DiskMetric.cpp.i
.PHONY : src/DiskMetric.i

# target to preprocess a source file
src/DiskMetric.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oop.dir/build.make CMakeFiles/oop.dir/src/DiskMetric.cpp.i
.PHONY : src/DiskMetric.cpp.i

src/DiskMetric.s: src/DiskMetric.cpp.s
.PHONY : src/DiskMetric.s

# target to generate assembly for a file
src/DiskMetric.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oop.dir/build.make CMakeFiles/oop.dir/src/DiskMetric.cpp.s
.PHONY : src/DiskMetric.cpp.s

src/HardwareMetric.o: src/HardwareMetric.cpp.o
.PHONY : src/HardwareMetric.o

# target to build an object file
src/HardwareMetric.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oop.dir/build.make CMakeFiles/oop.dir/src/HardwareMetric.cpp.o
.PHONY : src/HardwareMetric.cpp.o

src/HardwareMetric.i: src/HardwareMetric.cpp.i
.PHONY : src/HardwareMetric.i

# target to preprocess a source file
src/HardwareMetric.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oop.dir/build.make CMakeFiles/oop.dir/src/HardwareMetric.cpp.i
.PHONY : src/HardwareMetric.cpp.i

src/HardwareMetric.s: src/HardwareMetric.cpp.s
.PHONY : src/HardwareMetric.s

# target to generate assembly for a file
src/HardwareMetric.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oop.dir/build.make CMakeFiles/oop.dir/src/HardwareMetric.cpp.s
.PHONY : src/HardwareMetric.cpp.s

src/Logger.o: src/Logger.cpp.o
.PHONY : src/Logger.o

# target to build an object file
src/Logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oop.dir/build.make CMakeFiles/oop.dir/src/Logger.cpp.o
.PHONY : src/Logger.cpp.o

src/Logger.i: src/Logger.cpp.i
.PHONY : src/Logger.i

# target to preprocess a source file
src/Logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oop.dir/build.make CMakeFiles/oop.dir/src/Logger.cpp.i
.PHONY : src/Logger.cpp.i

src/Logger.s: src/Logger.cpp.s
.PHONY : src/Logger.s

# target to generate assembly for a file
src/Logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oop.dir/build.make CMakeFiles/oop.dir/src/Logger.cpp.s
.PHONY : src/Logger.cpp.s

src/Machine.o: src/Machine.cpp.o
.PHONY : src/Machine.o

# target to build an object file
src/Machine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oop.dir/build.make CMakeFiles/oop.dir/src/Machine.cpp.o
.PHONY : src/Machine.cpp.o

src/Machine.i: src/Machine.cpp.i
.PHONY : src/Machine.i

# target to preprocess a source file
src/Machine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oop.dir/build.make CMakeFiles/oop.dir/src/Machine.cpp.i
.PHONY : src/Machine.cpp.i

src/Machine.s: src/Machine.cpp.s
.PHONY : src/Machine.s

# target to generate assembly for a file
src/Machine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oop.dir/build.make CMakeFiles/oop.dir/src/Machine.cpp.s
.PHONY : src/Machine.cpp.s

src/MemoryMetric.o: src/MemoryMetric.cpp.o
.PHONY : src/MemoryMetric.o

# target to build an object file
src/MemoryMetric.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oop.dir/build.make CMakeFiles/oop.dir/src/MemoryMetric.cpp.o
.PHONY : src/MemoryMetric.cpp.o

src/MemoryMetric.i: src/MemoryMetric.cpp.i
.PHONY : src/MemoryMetric.i

# target to preprocess a source file
src/MemoryMetric.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oop.dir/build.make CMakeFiles/oop.dir/src/MemoryMetric.cpp.i
.PHONY : src/MemoryMetric.cpp.i

src/MemoryMetric.s: src/MemoryMetric.cpp.s
.PHONY : src/MemoryMetric.s

# target to generate assembly for a file
src/MemoryMetric.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oop.dir/build.make CMakeFiles/oop.dir/src/MemoryMetric.cpp.s
.PHONY : src/MemoryMetric.cpp.s

src/Menu.o: src/Menu.cpp.o
.PHONY : src/Menu.o

# target to build an object file
src/Menu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oop.dir/build.make CMakeFiles/oop.dir/src/Menu.cpp.o
.PHONY : src/Menu.cpp.o

src/Menu.i: src/Menu.cpp.i
.PHONY : src/Menu.i

# target to preprocess a source file
src/Menu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oop.dir/build.make CMakeFiles/oop.dir/src/Menu.cpp.i
.PHONY : src/Menu.cpp.i

src/Menu.s: src/Menu.cpp.s
.PHONY : src/Menu.s

# target to generate assembly for a file
src/Menu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oop.dir/build.make CMakeFiles/oop.dir/src/Menu.cpp.s
.PHONY : src/Menu.cpp.s

src/Metric.o: src/Metric.cpp.o
.PHONY : src/Metric.o

# target to build an object file
src/Metric.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oop.dir/build.make CMakeFiles/oop.dir/src/Metric.cpp.o
.PHONY : src/Metric.cpp.o

src/Metric.i: src/Metric.cpp.i
.PHONY : src/Metric.i

# target to preprocess a source file
src/Metric.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oop.dir/build.make CMakeFiles/oop.dir/src/Metric.cpp.i
.PHONY : src/Metric.cpp.i

src/Metric.s: src/Metric.cpp.s
.PHONY : src/Metric.s

# target to generate assembly for a file
src/Metric.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oop.dir/build.make CMakeFiles/oop.dir/src/Metric.cpp.s
.PHONY : src/Metric.cpp.s

src/NetworkMetric.o: src/NetworkMetric.cpp.o
.PHONY : src/NetworkMetric.o

# target to build an object file
src/NetworkMetric.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oop.dir/build.make CMakeFiles/oop.dir/src/NetworkMetric.cpp.o
.PHONY : src/NetworkMetric.cpp.o

src/NetworkMetric.i: src/NetworkMetric.cpp.i
.PHONY : src/NetworkMetric.i

# target to preprocess a source file
src/NetworkMetric.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oop.dir/build.make CMakeFiles/oop.dir/src/NetworkMetric.cpp.i
.PHONY : src/NetworkMetric.cpp.i

src/NetworkMetric.s: src/NetworkMetric.cpp.s
.PHONY : src/NetworkMetric.s

# target to generate assembly for a file
src/NetworkMetric.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oop.dir/build.make CMakeFiles/oop.dir/src/NetworkMetric.cpp.s
.PHONY : src/NetworkMetric.cpp.s

src/ThresholdMetric.o: src/ThresholdMetric.cpp.o
.PHONY : src/ThresholdMetric.o

# target to build an object file
src/ThresholdMetric.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oop.dir/build.make CMakeFiles/oop.dir/src/ThresholdMetric.cpp.o
.PHONY : src/ThresholdMetric.cpp.o

src/ThresholdMetric.i: src/ThresholdMetric.cpp.i
.PHONY : src/ThresholdMetric.i

# target to preprocess a source file
src/ThresholdMetric.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oop.dir/build.make CMakeFiles/oop.dir/src/ThresholdMetric.cpp.i
.PHONY : src/ThresholdMetric.cpp.i

src/ThresholdMetric.s: src/ThresholdMetric.cpp.s
.PHONY : src/ThresholdMetric.s

# target to generate assembly for a file
src/ThresholdMetric.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oop.dir/build.make CMakeFiles/oop.dir/src/ThresholdMetric.cpp.s
.PHONY : src/ThresholdMetric.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oop.dir/build.make CMakeFiles/oop.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oop.dir/build.make CMakeFiles/oop.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oop.dir/build.make CMakeFiles/oop.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... oop"
	@echo "... src/Alert.o"
	@echo "... src/Alert.i"
	@echo "... src/Alert.s"
	@echo "... src/CPUMetric.o"
	@echo "... src/CPUMetric.i"
	@echo "... src/CPUMetric.s"
	@echo "... src/DiskMetric.o"
	@echo "... src/DiskMetric.i"
	@echo "... src/DiskMetric.s"
	@echo "... src/HardwareMetric.o"
	@echo "... src/HardwareMetric.i"
	@echo "... src/HardwareMetric.s"
	@echo "... src/Logger.o"
	@echo "... src/Logger.i"
	@echo "... src/Logger.s"
	@echo "... src/Machine.o"
	@echo "... src/Machine.i"
	@echo "... src/Machine.s"
	@echo "... src/MemoryMetric.o"
	@echo "... src/MemoryMetric.i"
	@echo "... src/MemoryMetric.s"
	@echo "... src/Menu.o"
	@echo "... src/Menu.i"
	@echo "... src/Menu.s"
	@echo "... src/Metric.o"
	@echo "... src/Metric.i"
	@echo "... src/Metric.s"
	@echo "... src/NetworkMetric.o"
	@echo "... src/NetworkMetric.i"
	@echo "... src/NetworkMetric.s"
	@echo "... src/ThresholdMetric.o"
	@echo "... src/ThresholdMetric.i"
	@echo "... src/ThresholdMetric.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

